### ISSUE TITLE
add versioned javadoc in gh-pages

### ISSUE THREAD

**Issue by swissiety** [secure-software-engineering/actions#7]
include a (default) option to publish Javadoc into gh-pages as well.
goal: have one version for latest and one for each of the releases - which then can be linked in the respective website 

general example (stolen from SootUp)
```
  publish-javadoc:
    needs: Compilation
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: gh-pages
          java-version: 17
          target-folder: apidocs

```
